name: Build S20FE (Based AOSP A16)

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME : "galaxy_s20_fe"
  DEVICE_CODENAME : "r8s"

  CUSTOM_CMDS : "CROSS_COMPILE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LLVM=1 LLVM_IAS=1"

  KERNEL_SOURCE : "https://github.com/redmax19/android_kernel_samsung_universal9830.git"
  KERNEL_BRANCH : "main"

  CLANG_SOURCE : "https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git"
  CLANG_BRANCH : "lineage-20.0"

  GCC_GNU : false
  GCC_64_SOURCE : ""
  GCC_64_BRANCH : ""
  GCC_32_SOURCE : ""
  GCC_32_BRANCH : ""

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "exynos9830_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  KERNELSU_SOURCE : ""
  KERNELSU_BRANCH : ""

  KERNELSU_AUTO_GET : "true"
  KERNELSU_AUTO_FORK : "sukisu" # xxksu, rsuntk, next, resukisu and sukisu

  SUSFS_ENABLE : true
  SUSFS_FIXED : true

  AK3_SOURCE : "https://github.com/redmax19/AnyKernel3.git"
  AK3_BRANCH : "master"

  BOOT_SOURCE : ""

  NEED_DTBO : false
  NEED_SAFE_DTBO : false

  ROM_TEXT : "aosp_a16"

  # Other env
  PYTHON_VERSION: "3"

  PACK_METHOD: "Anykernel3"
  PACK_KMODULES: "false"

  KERNELSU_METHOD: "shell"

  PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches"
  PATCHES_BRANCH: "samsung_kernel" 
  

  SUSFS_FOLDER_FIXED: "a71_sm7150"
  SUSFS_PATCH_FIXED: "susfs_fixed"

  REKERNEL_ENABLE: "true"
  DROIDSPACES_ENABLE: "false"
  NOMOUNT_ENABLE: "true"

  HOOK_METHOD: "syscall"

  KERNEL_PATCH: "false"

  KPM_ENABLE: "false"
  KPM_INLINE: "false"
  KPM_KPATCH_NEXT: "false"
  KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux"

  BASEBAND_GUARD_ENABLE: "false"
  BASEBAND_GUARD_BOOT: "false"

  GENERATE_DTB: "false"
  GENERATE_CHIP: "qcom"

  BUILD_DEBUGGER: "false"
  SKIP_PATCH: "false"

  BUILD_OTHER_CONFIG: "true"
  MERGE_CONFIG_FILES: "r8s.config"

  FREE_MORE_SPACE: "false"

jobs:
  build-kernel:
    name: S20FE (Based AOSP A16)
    runs-on: ubuntu-latest
    
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v7

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get neccssary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🪛 Extra Kernel Options
        run: |
          # Only ${{ env.DEVICE_NAME }} use it.
          cd $GITHUB_WORKSPACE/device_kernel

          # enable CONFIG_TMPFS_XATTR

          echo "CONFIG_TMPFS_XATTR=y" >> ./arch/${{ env.KERNEL_ARCH }}/configs/${{ env.DEFCONFIG_NAME }}

      - name: 🧰 Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: 🔒 Patch Kernel of Baseband Guard
        uses: ./.github/workflows/patch-baseband-guard

      - name: ❌ Set Swap
        uses: thejerrybao/setup-swap-space@v1
        with:
            swap-space-path: /swapfile
            swap-size-gb: 16
            remove-existing-swap-files: true

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files
